DROP DATABASE IF EXISTS crud;
CREATE DATABASE crud;
USE crud;

DROP TABLE IF EXISTS users;
CREATE TABLE users (
    id INT(100) NOT NULL AUTO_INCREMENT,
    username CHAR(10) NOT NULL,
    name VARCHAR(50) NULL,
    email VARCHAR(150) NOT NULL,
    password VARCHAR(255) NOT NULL,
    PRIMARY KEY (id)
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
